version: "3"

services:
  ####################### App Definition #######################
  winston-app:
    restart: on-failure
    image: winston-app:${GIT_COMMIT:-latest}
    container_name: winston-app
    ports:
      - 8080:8080
    build:
      context: ../
      dockerfile: build/package/Dockerfile
    environment:
      - WINSTON_SLACK_BOTTOKEN=${WINSTON_SLACK_BOTTOKEN:-bottoken}
      - WINSTON_SLACK_VERIFICATIONTOKEN=${WINSTON_SLACK_VERIFICATIONTOKEN:-verifytoken}
      - WINSTON_DATABASE_DBHOST=winston-database
    depends_on:
      - winston-database
    networks:
      - winston

  ####################### Database Definition #######################
  winston-database:
    restart: on-failure
    image: mongo
    container_name: winston-database
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME:-user}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD:-password}
    volumes:
      - mongo-data:/data/db
    networks:
      - winston

####################### Networks Definition #######################
networks:
  winston:
    driver: bridge

####################### Volumes Definition #######################
volumes:
  mongo-data:
